# Generated by Django 4.2.7 on 2023-12-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(default=None, max_length=100, verbose_name='Почта'),
        ),
    ]
