# Generated by Django 4.2.7 on 2023-12-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_description'),
        ('orders', '0008_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_detail',
            field=models.ManyToManyField(through='orders.OrderItem', to='shop.product', verbose_name='Детали заказа'),
        ),
    ]
